- hosts: elk_master_nodes
  tasks:
  - firewalld:
      port: "{{ elastic_http_port }}/tcp"
      immediate: yes
      permanent: true
      state: enabled
  - firewalld:
      port: "{{ elastic_nodes_port }}/tcp"
      immediate: yes
      permanent: true
      state: enabled

  roles:
    - role: elastic.elasticsearch
  vars:
    oss_version: true
    es_data_dirs:
      - "/opt/elasticsearch/data"
    es_log_dir: "/opt/elasticsearch/logs"
    es_java_install: true
    es_heap_size: "1g"
    es_config:
      cluster.name: "elk-cluster"
      cluster.initial_master_nodes: "{{ elastic_cluster_initial_master_nodes }}"
      discovery.seed_hosts: "{{ elastic_discovery_seed_hosts }}"
      http.port: "{{ elastic_http_port }}"
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
      network.host: '0.0.0.0'
    es_plugins:
     - plugin: ingest-attachment

- hosts: elk_data_nodes
  tasks:
  - firewalld:
      port: "{{ elastic_http_port }}/tcp"
      immediate: yes
      permanent: true
      state: enabled
  - firewalld:
      port: "{{ elastic_nodes_port }}/tcp"
      immediate: yes
      permanent: true
      state: enabled
  roles:
    - role: elastic.elasticsearch
  vars:
    oss_version: true
    es_data_dirs:
      - "/data/elasticsearch/data"
    es_log_dir: "/data/elasticsearch/logs"
    es_java_install: true
    es_config:
      cluster.name: "elk-cluster"
      cluster.initial_master_nodes: "{{ elastic_cluster_initial_master_nodes }}"
      discovery.seed_hosts: "{{ elastic_discovery_seed_hosts }}"
      http.port: "{{ elastic_http_port }}"
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
      network.host: '0.0.0.0'
    es_plugins:
      - plugin: ingest-attachment

