- hosts: kibana
  tasks:
  - firewalld:
      port: "{{ kibana_server_port }}/tcp"
      immediate: yes
      permanent: true
      state: enabled
  roles:
    - role: geerlingguy.kibana
      kibana_version: "oss-7.x"
      kibana_package: kibana-oss
  
