- hosts: logstash
  tasks:
  - firewalld:
      port: "{{ logstash_listen_port_beats }}/tcp"
      immediate: yes
      permanent: true
      state: enabled
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.logstash
      logstash_version: "oss-7.x"

