- hosts: nginx01
  tasks:
    - set_fact:        
        logstash_hosts: "{{ groups['logstash'] | map('extract',hostvars,'ansible_host') | list }}"
  roles:
    - role: elastic.beats
  vars:
    beats_version: 7.8.0
    oss_version: true
    beat: filebeat
    output_conf: 
     logstash:
      hosts:
       - {{ logstash_hosts[0] }}:5044
       - {{ logstash_hosts[1 }}:5044
    beat_conf:
      filebeat:
        filebeat.modules:
         - module: system
         - module: nginx
