- hosts: zabbix_srv
  roles:
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_become_on_localhost: false
      zabbix_install_pip_packages: true
      #zabbix_url: http://10.26.2.15/zabbix


      







