- hosts: elk_nginx
  tasks:
  - firewalld:
      port: "{{ zabbix_agent_listenport }}/tcp"
      immediate: yes
      permanent: true
      state: enabled
  roles:
    - role: dj-wasabi.zabbix-agent


      







