- hosts: nginx
  #mytest: "{{ hostvars.nginx}}"
  tasks:
    - set_fact:
        #mytest: "{{ hostvars.nginx.nginx01.ansible_host }}"
        #es_host: "{{ groups.nginx[0] }}"
        #es_host: "{{ hostvars.nginx01.ansible_host }}"
        #master_nodes: "{{ groups['elk_master_nodes'] | map('extract',hostvars,'ansible_host') | list }}"
        #master_nodes: "{{ groups['elk_master_nodes'] | map('extract',hostvars,'ansible_host') | list }}"
        #master_nodes:  "{{ groups['elk_master_nodes'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"
#  - debug: var=item
#  with_items: '{{ master_nodes }}'

    - debug: var=inventory_hostname
    - debug: var=groups.elk_master_nodes[0]
    - debug: var=ansible_host
    - debug: var=mytest
    - debug: var=master_nodes[0]


