- hosts: zabbix_db
  tasks:
  - firewalld:
      port: "{{ zabbix_server_dbport }}/tcp"
      immediate: yes
      permanent: true
      state: enabled
  - firewalld:
      port: "{{ javagateway_listenport }}/tcp"
      immediate: yes
      permanent: true
      state: enabled
  roles:
    - role: mysql
      mysql_users:
       - name: "{{ zabbix_server_dbuser }}"
         host: "%"
         password: "{{ zabbix_server_dbpassword }}"
         priv: "*.*:ALL"

- hosts: zabbix_srv
  tasks:
  - firewalld:
      port: "{{ zabbix_server_listenport }}/tcp"
      immediate: yes
      permanent: true
      state: enabled
  roles:
    - role: zabbix-server
      zabbix_url: "{{ ansible_host }}"
      zabbix_server_real_dbhost: "{{ zabbix_server_dbhost }}"
      zabbix_server_mysql_login_host: "{{ zabbix_server_dbhost }}"


- hosts: zabbix_web
  tasks:
  - firewalld:
      port: "{{ zabbix_apache_vhost_port }}/tcp"
      immediate: yes
      permanent: true
      state: enabled
  roles:
    - role: apache
    - role: zabbix-web
      zabbix_vhost: true      
      



