- hosts: zabbix_db
  tasks:
  - firewalld:
      port: 3306/tcp
      immediate: yes
      permanent: true
      state: enabled
  roles:
    - role: geerlingguy.mysql
      mysql_users:
       - name: zabbix-server
         host: "%"
         password: zabbix-server
         priv: "*.*:ALL"


- hosts: zabbix_srv
  tasks:
  - firewalld:
      port: 10051/tcp
      immediate: yes
      permanent: true
      state: enabled
  roles:
    - role: dj-wasabi.zabbix-server
      zabbix_selinux: true
      zabbix_url: "{{ ansible_host }}"
      zabbix_server_dbhost: 10.26.2.16
      zabbix_server_real_dbhost: 10.26.2.16
      zabbix_server_dbport: 3306
      zabbix_server_database: mysql
      zabbix_database_type: mysql
      zabbix_server_database_long: mysql
      zabbix_server_mysql_login_host: 10.26.2.16
      zabbix_server_mysql_login_user: zabbix-server
      zabbix_server_mysql_login_password: zabbix-server      
      zabbix_server_dbuser: zabbix-server
      zabbix_server_dbpassword: zabbix-server

- hosts: zabbix_web
  tasks:
  - firewalld:
      port: 80/tcp
      immediate: yes
      permanent: true
      state: enabled
  roles:
    - role: geerlingguy.apache
    - role: dj-wasabi.zabbix-web
      zabbix_server_hostname: 10.26.2.18
      zabbix_url: "{{ ansible_host }}"
      zabbix_vhost: false
      zabbix_server_dbhost: 10.26.2.16
      zabbix_server_dbport: 3306      
      zabbix_server_database: mysql
      zabbix_server_database_long: mysql


